/:
  controller: "MainController"
  action: "home"

/user/add:
  controller: "UserController"
  action: "register"

/user/delete:
  controller: "UserController"
  action: "delete"

/se-connecter:
  controller: "UserController"
  action: "login"

/se-deconnecter:
  controller: "UserController"
  action: "logout"

/backoffice:
  controller: "BackofficeController"
  action: "dashboard"

/page:
  controller: "PageController"
  action: "show"